In [1]:
# get common values from 2 set

In [2]:
s1 = {1,2,3,4,5,6}
s2 = {2,4,6,8,12}

s1.intersection(s2)

{2, 4, 6}

In [3]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 8, 12}

In [4]:
s1-s2

{1, 3, 5}

In [5]:
s2-s1

{8, 12}

In [6]:
# check if number palindrome -

In [7]:
def num_palin(num):
    temp = num
    rev = 0
    
    while(temp>=1):
        digit = temp%10
        rev = rev*10 + digit
        temp = temp//10
    
    if(rev==num):
        print("Palindrome")
    else:
        print("Not Palindrome")

In [8]:
num_palin(12321)

Palindrome


In [9]:
num_palin(1234)

Not Palindrome


In [10]:
# string palindrome

In [11]:
def str_palin(s):
    rev = s[::-1]
    
    if(rev==s):
        print("Palindrome")
    else:
        print("Not Palindrome")
    

In [12]:
str_palin("radar")

Palindrome


In [13]:
str_palin("radppr")

Not Palindrome


In [14]:
def str_palin2(s):
    n = len(s)
    flag = True
    
    for i in range(n):
        # print(s[n-1-i],"\t",s[i])
        if(s[i]==s[n-1-i]):
            flag=True
        else:
            flag=False
            break;
            
    if flag:
        print("Palindrome")
    else:
        print("Not Palindrome")

In [15]:
str_palin2("radpar")

Not Palindrome


In [16]:
# Pattern Printing

In [17]:
for i in range(1,6): # 1 to 5
    for j in range(1,i+1): # 1 to 5
        print(i , end=" ")
    print("\n")

1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



In [18]:
for i in range(1,6): # i = 1 to 5
    for j in range(1, i+1): # 1 to i
        print("#" , end=" ")
    print("\n")

# 

# # 

# # # 

# # # # 

# # # # # 



In [19]:
def pattern1(n):
    for i in range(1, n+1):
        for j in range(1, i+1):
            print(i , end=" ")
        print("\n")
        
pattern1(4)

1 

2 2 

3 3 3 

4 4 4 4 



In [20]:
def pattern2(n):
    for i in range(0,n+1): # i from 0 to n
        for j in range(0, i+1): # j from 0 to i
            print(j , end=" ")
        print("\n")
        
pattern2(4)

0 

0 1 

0 1 2 

0 1 2 3 

0 1 2 3 4 



In [21]:
for i in range(1,4+1): # 1 to 4
    alpha = ord("A")-1 # alpha = 65
    
    for j in range(1,i+1): # 1 to i
        print(chr(alpha+i) , end=" ")
    print("\n")

A 

B B 

C C C 

D D D D 



In [22]:
def alpha_pattern(n):
    s_al = ord("A")    
    for i in range(0,n):
        for j in range(0,i+1):
            print(chr(i+s_al) , end=" ")
        print("\n")
    
alpha_pattern(4)

A 

B B 

C C C 

D D D D 



In [23]:
n = 3
x = 0
A_ascii = ord("A")

for i in range(0,n):
    for j in range(0,i+1):
        print(chr(A_ascii + x) , end=" ")
        x=x+1
    print("\n")

A 

B C 

D E F 



In [24]:
def alpha_pttern2(n):
    x = 0
    A_ascii = ord("A")

    for i in range(0,n):
        for j in range(0,i+1):
            print(chr(A_ascii + x) , end=" ")
            x=x+1
        print("\n")   
        
alpha_pttern2(4)

A 

B C 

D E F 

G H I J 



In [25]:
# increment values of all the keys

d1 = {"k1":10 , "k2":20 , "k3":30}

for k in d1.keys():
    d1[k] = d1[k]+100
    
print(d1.values())

dict_values([110, 120, 130])


In [26]:
import random

# creates a random value from [0,1)
n = random.random()
print(n)

0.04042484837170057


In [27]:
import random

# creates a random value from [a,b]
n = random.randint(10,20)
print(n)

14


In [28]:
# numpy random array

In [29]:
from numpy import random

In [30]:
ar1 = random.random(size=5)

ar1

array([0.96298558, 0.39506991, 0.20218431, 0.5671567 , 0.8622591 ])

In [31]:
ar2 = random.randint(10,40, size=4)

ar2

array([28, 18, 24, 20])

In [32]:
ar3 = random.randint(low=10 ,  high=40, size=(2,3))

ar3

array([[39, 15, 22],
       [30, 22, 32]])

In [33]:
r1 = random.randint(low=10 , high=50)

r1

44

In [34]:
r2 = random.rand()

r2

0.6306398240636857

In [35]:
# example of *args :-

def summation(*args):
    res = 0
    
    #print(args)
    #print(type(args))
    
    for x in args:
        res = res+x
    
    print(res)

# way 1 -
summation(2,4,6)

# way 2 -
nums_list = [5,10,15]
summation(*nums_list)

12
30


In [36]:
def print_args(*args):
    for val in args:
        print(val , end=" ")
        
# way 1 -
print_args("hello","world","hi","there")
print("\n")

# way 2 -
s_list = ["bye","world","see you","again"]
print_args(*s_list)

hello world hi there 

bye world see you again 

In [37]:
# example of **kwargs -

def print_details(**details):
    
    for key,value in details.items():
        print(f"{key} is {value}")
        
# way 1 -
print_details(first_name="Kamaru", last_name="Usman")

print("\n")

# way 2 -
dets = {"first_name" : "Charles" , "last_name" : "Oliviera" , "weight_class" : "Light-weight"}
print_details(**dets)

first_name is Kamaru
last_name is Usman


first_name is Charles
last_name is Oliviera
weight_class is Light-weight


In [38]:
# call by value -

def change_string(s):
    s = s + " ~~ new  changes"
    print("Inside Function - ",s)
    
s = "Hello World"
change_string(s)
print("Outside Function - ",s)

Inside Function -  Hello World ~~ new  changes
Outside Function -  Hello World


In [39]:
# call by reference -

def change_list(l):
    l.append(999)
    l.append("NEW VALUE")
    
    print("Inside Function - ", l)

l = [1,2,3,4]
change_list(l)
print("Outside Function - ", l)

Inside Function -  [1, 2, 3, 4, 999, 'NEW VALUE']
Outside Function -  [1, 2, 3, 4, 999, 'NEW VALUE']


In [40]:
nums = [1,2,3]

nums*2

[1, 2, 3, 1, 2, 3]

In [41]:
# armstrong number -

def arm_strong(num):
    temp = num
    arm = 0
    
    while(temp>=1):
        digit = temp%10
        arm = arm + digit**3
        temp = temp//10
    
    if(arm == num):
        print("Armstrong")
    else:
        print("Not Armstrong")

In [42]:
arm_strong(477)

Not Armstrong


In [43]:
def armstrong_till(n):
    for num in range(1,n):
        temp = num
        arm = 0
        while(temp>=1):
            digit = temp%10
            arm = arm + digit**3
            temp = temp//10
    
        if(arm == num):
            print("Armstrong - ", arm)

In [44]:
armstrong_till(500)

Armstrong -  1
Armstrong -  153
Armstrong -  370
Armstrong -  371
Armstrong -  407


In [45]:
# armstrong number -

def arm_strong_2(num):
    temp = num
    arm = 0
    
    while(temp>=1):
        digit = temp%10
        arm = arm + digit**3
        temp = temp//10
    
    if(arm == num):
        return True
    else:
        return False
        

def first_m_arm(m):
    count = 0
    i=1
    while True:
        if arm_strong_2(i) :
            print(i)
            count +=1
        i = i + 1
        
        if(count==m):
            break

In [46]:
first_m_arm(5)

1
153
370
371
407


In [47]:
# perfect number - 6, 28 etc

In [48]:
def perf_num(num):
    addn = 0
    for i in range (1, (num//2) + 1):
        if num%i==0:
            addn = addn+i
    # for ends
    
    if (num == addn):
        print("perfect Number")
    else:
        print("Not Perfect")
        
perf_num(61)

Not Perfect


In [49]:
# strong number 
# 145 = 1! + 4! + 5!

In [50]:
def fctrl(num):
    if num<=1:
        return 1
    else: 
        return num * fctrl(num-1)

def strong_num(num):
    temp = num
    strong = 0
    
    while(temp>=1):
        dig = temp%10
        strong = strong + fctrl(dig)
        temp = temp//10
    
    if(strong==num):
        print("Strong")
    else:
        print("Not Strong")
    
strong_num(145)

Strong


In [51]:
# 2nd max num from list

size = int( input("Enter the size of list : ") )

sample = []

for i in range(size):
    el = int( input(f'Enter element {i+1} : ') )
    sample.append(el)

sample.sort(reverse=True)
print(sample)
print(f'Second Max = {sample[1]}')

Enter the size of list : 1
Enter element 1 : 1
[1]


IndexError: list index out of range

In [52]:
def swap_logic(nums):
    size = len(nums)
    
    temp = nums[0]
    nums[0] = nums[size-1]
    nums[size-1] = temp

nums = [1,2,3,4,5]
swap_logic(nums)
print(nums)

[5, 2, 3, 4, 1]


In [53]:
# num of vowels in a string -

In [54]:
vowels = "a e i o u".split(" ")

inp_str = "Orange"

vow_list = [x for x in inp_str.lower() if x in vowels]

print(len( vow_list) )

3


In [55]:
vowels = "a e i o u".split(" ")
inp_str = "Orange"
new_list = []

for el in inp_str:
    if el in vowels:
        new_list.append(el)
        
print(len( new_list) )

2


In [56]:
inp_list = [1,2,2,3,4,4,6,7]
res = []

for el in inp_list:
    if el not in res:
        res.append(el)

res

[1, 2, 3, 4, 6, 7]

In [60]:
# exception handling

try:
    num = int( input("Enter Numerator : ") )
    div = int ( input("Input Divisor :") )
    
    print(num/div)
except ex:
    print("Exception occured - ", ex)
else: 
    print("No exception occured")
finally:
    print("executed regardless")

Enter Numerator : 2
Input Divisor :1
2.0
No exception occured
executed regardless
